/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedMocksRouteImport } from './routes/_authenticated/mocks'
import { Route as AuthenticatedPyqRouteImport } from './routes/_authenticated/pyq'
import { Route as AuthenticatedRevisionRouteImport } from './routes/_authenticated/revision'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin/exams'
import { Route as AuthenticatedAdminSourcesRouteImport } from './routes/_authenticated/admin/sources'
import { Route as AuthenticatedAdminSyllabusRouteImport } from './routes/_authenticated/admin/syllabus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMocksRoute = AuthenticatedMocksRouteImport.update({
  id: '/mocks',
  path: '/mocks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPyqRoute = AuthenticatedPyqRouteImport.update({
  id: '/pyq',
  path: '/pyq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisionRoute = AuthenticatedRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSourcesRoute =
  AuthenticatedAdminSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSyllabusRoute =
  AuthenticatedAdminSyllabusRouteImport.update({
    id: '/syllabus',
    path: '/syllabus',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/mocks': typeof AuthenticatedMocksRoute
  '/pyq': typeof AuthenticatedPyqRoute
  '/revision': typeof AuthenticatedRevisionRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/today': typeof AuthenticatedTodayRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/admin/syllabus': typeof AuthenticatedAdminSyllabusRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/mocks': typeof AuthenticatedMocksRoute
  '/pyq': typeof AuthenticatedPyqRoute
  '/revision': typeof AuthenticatedRevisionRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/today': typeof AuthenticatedTodayRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/admin/syllabus': typeof AuthenticatedAdminSyllabusRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/mocks': typeof AuthenticatedMocksRoute
  '/_authenticated/pyq': typeof AuthenticatedPyqRoute
  '/_authenticated/revision': typeof AuthenticatedRevisionRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/_authenticated/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/_authenticated/admin/syllabus': typeof AuthenticatedAdminSyllabusRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/analytics'
    | '/learn'
    | '/mocks'
    | '/pyq'
    | '/revision'
    | '/roadmap'
    | '/today'
    | '/admin/exams'
    | '/admin/sources'
    | '/admin/syllabus'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/learn'
    | '/mocks'
    | '/pyq'
    | '/revision'
    | '/roadmap'
    | '/today'
    | '/admin/exams'
    | '/admin/sources'
    | '/admin/syllabus'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/learn'
    | '/_authenticated/mocks'
    | '/_authenticated/pyq'
    | '/_authenticated/revision'
    | '/_authenticated/roadmap'
    | '/_authenticated/today'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/sources'
    | '/_authenticated/admin/syllabus'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mocks': {
      id: '/_authenticated/mocks'
      path: '/mocks'
      fullPath: '/mocks'
      preLoaderRoute: typeof AuthenticatedMocksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pyq': {
      id: '/_authenticated/pyq'
      path: '/pyq'
      fullPath: '/pyq'
      preLoaderRoute: typeof AuthenticatedPyqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revision': {
      id: '/_authenticated/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof AuthenticatedRevisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sources': {
      id: '/_authenticated/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AuthenticatedAdminSourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/syllabus': {
      id: '/_authenticated/admin/syllabus'
      path: '/syllabus'
      fullPath: '/admin/syllabus'
      preLoaderRoute: typeof AuthenticatedAdminSyllabusRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRoute
  AuthenticatedAdminSourcesRoute: typeof AuthenticatedAdminSourcesRoute
  AuthenticatedAdminSyllabusRoute: typeof AuthenticatedAdminSyllabusRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRoute,
    AuthenticatedAdminSourcesRoute: AuthenticatedAdminSourcesRoute,
    AuthenticatedAdminSyllabusRoute: AuthenticatedAdminSyllabusRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedMocksRoute: typeof AuthenticatedMocksRoute
  AuthenticatedPyqRoute: typeof AuthenticatedPyqRoute
  AuthenticatedRevisionRoute: typeof AuthenticatedRevisionRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedMocksRoute: AuthenticatedMocksRoute,
  AuthenticatedPyqRoute: AuthenticatedPyqRoute,
  AuthenticatedRevisionRoute: AuthenticatedRevisionRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
